//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnaAndSarahWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnnaSarahEntities : DbContext
    {
        public AnnaSarahEntities()
            : base("name=AnnaSarahEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblProductDetail> tblProductDetails { get; set; }
        public virtual DbSet<tblTagCategory> tblTagCategories { get; set; }
        public virtual DbSet<tblTag> tblTags { get; set; }
        public virtual DbSet<vw_category_product> vw_category_product { get; set; }
        public virtual DbSet<vw_kat_detail> vw_kat_detail { get; set; }
        public virtual DbSet<vw_tag_cat_product> vw_tag_cat_product { get; set; }
        public virtual DbSet<tbl_SubscribeList> tbl_SubscribeList { get; set; }
        public virtual DbSet<tblContact> tblContacts { get; set; }
        public virtual DbSet<tblBanner> tblBanners { get; set; }
        public virtual DbSet<tblBlog> tblBlogs { get; set; }
        public virtual DbSet<tblBlogCategory> tblBlogCategories { get; set; }
        public virtual DbSet<tblComment> tblComments { get; set; }
        public virtual DbSet<vw_blog_category> vw_blog_category { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblWebUser> tblWebUsers { get; set; }
    }
}
