//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnaAndSarahWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubscribeList
    {
        public int Sid { get; set; }
        public string MailAddress { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
