//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnaAndSarahWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlog
    {
        public int Bid { get; set; }
        public string BAd { get; set; }
        public string BAciklama { get; set; }
        public string BText { get; set; }
        public string BResim { get; set; }
        public Nullable<int> Cid { get; set; }
        public string Yazar { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> OkunmaSayisi { get; set; }
        public string UrlRewrite { get; set; }
    }
}
