//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnaAndSarahWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBanner
    {
        public int Bid { get; set; }
        public string BannerHeader { get; set; }
        public string BannerText { get; set; }
        public string BannerImage { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public string Link { get; set; }
    }
}
