//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnaAndSarahWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComment
    {
        public int Cid { get; set; }
        public string Comment { get; set; }
        public string Email { get; set; }
        public Nullable<int> Bid { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
