//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnaAndSarahWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact
    {
        public int Cid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Topic { get; set; }
        public string Text { get; set; }
    }
}
