//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnaAndSarahWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductDetail
    {
        public int Cid { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Link { get; set; }
        public string Company { get; set; }
        public string Country { get; set; }
        public string Ingredients { get; set; }
        public string ServingSize { get; set; }
        public string Calories { get; set; }
        public string Calories_from_fat { get; set; }
        public string Total_Fat { get; set; }
        public string Total_Fat_Yuzde { get; set; }
        public string Saturated_Fat { get; set; }
        public string Saturated_Fat_Yuzde { get; set; }
        public string Trans_Fat { get; set; }
        public string Trans_Fat_Yuzde { get; set; }
        public string Cholesterol { get; set; }
        public string Cholesterol_Yuzde { get; set; }
        public string Sodium { get; set; }
        public string Sodium_Yuzde { get; set; }
        public string Total_Carbonhydrate { get; set; }
        public string Total_Carbonhydrate_Yuzde { get; set; }
        public string Dietary_Fiber { get; set; }
        public string Dietary_Fiber_Yuzde { get; set; }
        public string Sugar { get; set; }
        public string Sugar_Yuzde { get; set; }
        public string Protein { get; set; }
        public string Protein_Yuzde { get; set; }
        public string VitaminA_Yuzde { get; set; }
        public string VitaminC_Yuzde { get; set; }
        public string Calcium_Yuzde { get; set; }
        public string Iron_Yuzde { get; set; }
        public Nullable<int> CatId { get; set; }
        public string Weight { get; set; }
        public string Column1_Header { get; set; }
        public string Column1_Value { get; set; }
        public string Column2_Header { get; set; }
        public string Column2_Value { get; set; }
        public string Column3_Header { get; set; }
        public string Column3_Value { get; set; }
        public string Column4_Header { get; set; }
        public string Column4_Value { get; set; }
    }
}
