//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnaAndSarahWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_category_product
    {
        public int Cid { get; set; }
        public Nullable<int> CMainId { get; set; }
        public string CatName { get; set; }
        public string Image { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<int> SiraNo { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> SiraYeni { get; set; }
    }
}
