//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnaAndSarahWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_tag_cat_product
    {
        public string TagName { get; set; }
        public Nullable<int> TagId { get; set; }
        public string LinkUrl { get; set; }
        public string Image { get; set; }
        public string CatName { get; set; }
        public int Cid { get; set; }
    }
}
