//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galgale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PortalHaber_Icerik
    {
        public int HaberId { get; set; }
        public string HaberBaslik { get; set; }
        public string HaberAciklama { get; set; }
        public string HaberMetni { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public string HaberUrl { get; set; }
        public Nullable<int> KaynakId { get; set; }
        public Nullable<int> YazarId { get; set; }
        public string Etiketler { get; set; }
        public Nullable<bool> MansetDurum { get; set; }
        public Nullable<bool> UMansetDurum { get; set; }
        public Nullable<bool> AltManset_Durum { get; set; }
        public Nullable<int> Site_Id { get; set; }
    }
}
