//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galgale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PortalHaber_Yazar
    {
        public int YazarId { get; set; }
        public string YName { get; set; }
        public Nullable<int> Tipi { get; set; }
        public string Sifre { get; set; }
        public string EPosta { get; set; }
        public Nullable<int> Site_Id { get; set; }
    }
}
