#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberPortal.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB090928093827")]
	public partial class ManageDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_PortalHaber_IP(tbl_PortalHaber_IP instance);
    partial void Updatetbl_PortalHaber_IP(tbl_PortalHaber_IP instance);
    partial void Deletetbl_PortalHaber_IP(tbl_PortalHaber_IP instance);
    partial void Inserttbl_PortalHaber_kategori(tbl_PortalHaber_kategori instance);
    partial void Updatetbl_PortalHaber_kategori(tbl_PortalHaber_kategori instance);
    partial void Deletetbl_PortalHaber_kategori(tbl_PortalHaber_kategori instance);
    partial void Inserttbl_PortalHaber_OkunmaSayisi(tbl_PortalHaber_OkunmaSayisi instance);
    partial void Updatetbl_PortalHaber_OkunmaSayisi(tbl_PortalHaber_OkunmaSayisi instance);
    partial void Deletetbl_PortalHaber_OkunmaSayisi(tbl_PortalHaber_OkunmaSayisi instance);
    partial void Inserttbl_PortalHaber_Site(tbl_PortalHaber_Site instance);
    partial void Updatetbl_PortalHaber_Site(tbl_PortalHaber_Site instance);
    partial void Deletetbl_PortalHaber_Site(tbl_PortalHaber_Site instance);
    partial void Inserttbl_PortalHaber_Tip(tbl_PortalHaber_Tip instance);
    partial void Updatetbl_PortalHaber_Tip(tbl_PortalHaber_Tip instance);
    partial void Deletetbl_PortalHaber_Tip(tbl_PortalHaber_Tip instance);
    partial void Inserttbl_PortalHaber_Yazar(tbl_PortalHaber_Yazar instance);
    partial void Updatetbl_PortalHaber_Yazar(tbl_PortalHaber_Yazar instance);
    partial void Deletetbl_PortalHaber_Yazar(tbl_PortalHaber_Yazar instance);
    partial void Inserttbl_PortalHaber_YazarSiteRelation(tbl_PortalHaber_YazarSiteRelation instance);
    partial void Updatetbl_PortalHaber_YazarSiteRelation(tbl_PortalHaber_YazarSiteRelation instance);
    partial void Deletetbl_PortalHaber_YazarSiteRelation(tbl_PortalHaber_YazarSiteRelation instance);
    partial void Inserttbl_PortalHaber_Kaynak(tbl_PortalHaber_Kaynak instance);
    partial void Updatetbl_PortalHaber_Kaynak(tbl_PortalHaber_Kaynak instance);
    partial void Deletetbl_PortalHaber_Kaynak(tbl_PortalHaber_Kaynak instance);
    partial void Inserttbl_PortalHaber_Icerik(tbl_PortalHaber_Icerik instance);
    partial void Updatetbl_PortalHaber_Icerik(tbl_PortalHaber_Icerik instance);
    partial void Deletetbl_PortalHaber_Icerik(tbl_PortalHaber_Icerik instance);
    partial void Inserttbl_PortalHaber_Icerik2(tbl_PortalHaber_Icerik2 instance);
    partial void Updatetbl_PortalHaber_Icerik2(tbl_PortalHaber_Icerik2 instance);
    partial void Deletetbl_PortalHaber_Icerik2(tbl_PortalHaber_Icerik2 instance);
    #endregion
		
		public ManageDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB090928093827ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ManageDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ManageDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ManageDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ManageDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_PortalHaber_IP> tbl_PortalHaber_IPs
		{
			get
			{
				return this.GetTable<tbl_PortalHaber_IP>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PortalHaber_kategori> tbl_PortalHaber_kategoris
		{
			get
			{
				return this.GetTable<tbl_PortalHaber_kategori>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PortalHaber_OkunmaSayisi> tbl_PortalHaber_OkunmaSayisis
		{
			get
			{
				return this.GetTable<tbl_PortalHaber_OkunmaSayisi>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PortalHaber_Site> tbl_PortalHaber_Sites
		{
			get
			{
				return this.GetTable<tbl_PortalHaber_Site>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PortalHaber_Tip> tbl_PortalHaber_Tips
		{
			get
			{
				return this.GetTable<tbl_PortalHaber_Tip>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PortalHaber_Yazar> tbl_PortalHaber_Yazars
		{
			get
			{
				return this.GetTable<tbl_PortalHaber_Yazar>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PortalHaber_YazarSiteRelation> tbl_PortalHaber_YazarSiteRelations
		{
			get
			{
				return this.GetTable<tbl_PortalHaber_YazarSiteRelation>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PortalHaber_Kaynak> tbl_PortalHaber_Kaynaks
		{
			get
			{
				return this.GetTable<tbl_PortalHaber_Kaynak>();
			}
		}
		
		public System.Data.Linq.Table<VWBANNER> VWBANNERs
		{
			get
			{
				return this.GetTable<VWBANNER>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PortalHaber_Icerik> tbl_PortalHaber_Iceriks
		{
			get
			{
				return this.GetTable<tbl_PortalHaber_Icerik>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PortalHaber_Icerik2> tbl_PortalHaber_Icerik2s
		{
			get
			{
				return this.GetTable<tbl_PortalHaber_Icerik2>();
			}
		}
		
		public System.Data.Linq.Table<VWYHABERLIST> VWYHABERLISTs
		{
			get
			{
				return this.GetTable<VWYHABERLIST>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PortalHaber_IP")]
	public partial class tbl_PortalHaber_IP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IP_ID;
		
		private System.Nullable<int> _Haber_Id;
		
		private string _IP;
		
		private EntityRef<tbl_PortalHaber_Icerik> _tbl_PortalHaber_Icerik;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIP_IDChanging(int value);
    partial void OnIP_IDChanged();
    partial void OnHaber_IdChanging(System.Nullable<int> value);
    partial void OnHaber_IdChanged();
    partial void OnIPChanging(string value);
    partial void OnIPChanged();
    #endregion
		
		public tbl_PortalHaber_IP()
		{
			this._tbl_PortalHaber_Icerik = default(EntityRef<tbl_PortalHaber_Icerik>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IP_ID
		{
			get
			{
				return this._IP_ID;
			}
			set
			{
				if ((this._IP_ID != value))
				{
					this.OnIP_IDChanging(value);
					this.SendPropertyChanging();
					this._IP_ID = value;
					this.SendPropertyChanged("IP_ID");
					this.OnIP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Haber_Id", DbType="Int")]
		public System.Nullable<int> Haber_Id
		{
			get
			{
				return this._Haber_Id;
			}
			set
			{
				if ((this._Haber_Id != value))
				{
					if (this._tbl_PortalHaber_Icerik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHaber_IdChanging(value);
					this.SendPropertyChanging();
					this._Haber_Id = value;
					this.SendPropertyChanged("Haber_Id");
					this.OnHaber_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="VarChar(255)")]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this.OnIPChanging(value);
					this.SendPropertyChanging();
					this._IP = value;
					this.SendPropertyChanged("IP");
					this.OnIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Icerik_tbl_PortalHaber_IP", Storage="_tbl_PortalHaber_Icerik", ThisKey="Haber_Id", OtherKey="HaberId", IsForeignKey=true)]
		public tbl_PortalHaber_Icerik tbl_PortalHaber_Icerik
		{
			get
			{
				return this._tbl_PortalHaber_Icerik.Entity;
			}
			set
			{
				tbl_PortalHaber_Icerik previousValue = this._tbl_PortalHaber_Icerik.Entity;
				if (((previousValue != value) 
							|| (this._tbl_PortalHaber_Icerik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_PortalHaber_Icerik.Entity = null;
						previousValue.tbl_PortalHaber_IPs.Remove(this);
					}
					this._tbl_PortalHaber_Icerik.Entity = value;
					if ((value != null))
					{
						value.tbl_PortalHaber_IPs.Add(this);
						this._Haber_Id = value.HaberId;
					}
					else
					{
						this._Haber_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_PortalHaber_Icerik");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PortalHaber_kategori")]
	public partial class tbl_PortalHaber_kategori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kid;
		
		private string _KName;
		
		private EntitySet<tbl_PortalHaber_Icerik> _tbl_PortalHaber_Iceriks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKidChanging(int value);
    partial void OnKidChanged();
    partial void OnKNameChanging(string value);
    partial void OnKNameChanged();
    #endregion
		
		public tbl_PortalHaber_kategori()
		{
			this._tbl_PortalHaber_Iceriks = new EntitySet<tbl_PortalHaber_Icerik>(new Action<tbl_PortalHaber_Icerik>(this.attach_tbl_PortalHaber_Iceriks), new Action<tbl_PortalHaber_Icerik>(this.detach_tbl_PortalHaber_Iceriks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kid
		{
			get
			{
				return this._Kid;
			}
			set
			{
				if ((this._Kid != value))
				{
					this.OnKidChanging(value);
					this.SendPropertyChanging();
					this._Kid = value;
					this.SendPropertyChanged("Kid");
					this.OnKidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KName", DbType="VarChar(255)")]
		public string KName
		{
			get
			{
				return this._KName;
			}
			set
			{
				if ((this._KName != value))
				{
					this.OnKNameChanging(value);
					this.SendPropertyChanging();
					this._KName = value;
					this.SendPropertyChanged("KName");
					this.OnKNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_kategori_tbl_PortalHaber_Icerik", Storage="_tbl_PortalHaber_Iceriks", ThisKey="Kid", OtherKey="KategoriId")]
		public EntitySet<tbl_PortalHaber_Icerik> tbl_PortalHaber_Iceriks
		{
			get
			{
				return this._tbl_PortalHaber_Iceriks;
			}
			set
			{
				this._tbl_PortalHaber_Iceriks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PortalHaber_Iceriks(tbl_PortalHaber_Icerik entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_kategori = this;
		}
		
		private void detach_tbl_PortalHaber_Iceriks(tbl_PortalHaber_Icerik entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_kategori = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PortalHaber_OkunmaSayisi")]
	public partial class tbl_PortalHaber_OkunmaSayisi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OS_Id;
		
		private System.Nullable<int> _Haber_ID;
		
		private System.Nullable<int> _OkunmaSayisi;
		
		private EntityRef<tbl_PortalHaber_Icerik> _tbl_PortalHaber_Icerik;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOS_IdChanging(int value);
    partial void OnOS_IdChanged();
    partial void OnHaber_IDChanging(System.Nullable<int> value);
    partial void OnHaber_IDChanged();
    partial void OnOkunmaSayisiChanging(System.Nullable<int> value);
    partial void OnOkunmaSayisiChanged();
    #endregion
		
		public tbl_PortalHaber_OkunmaSayisi()
		{
			this._tbl_PortalHaber_Icerik = default(EntityRef<tbl_PortalHaber_Icerik>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OS_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OS_Id
		{
			get
			{
				return this._OS_Id;
			}
			set
			{
				if ((this._OS_Id != value))
				{
					this.OnOS_IdChanging(value);
					this.SendPropertyChanging();
					this._OS_Id = value;
					this.SendPropertyChanged("OS_Id");
					this.OnOS_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Haber_ID", DbType="Int")]
		public System.Nullable<int> Haber_ID
		{
			get
			{
				return this._Haber_ID;
			}
			set
			{
				if ((this._Haber_ID != value))
				{
					if (this._tbl_PortalHaber_Icerik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHaber_IDChanging(value);
					this.SendPropertyChanging();
					this._Haber_ID = value;
					this.SendPropertyChanged("Haber_ID");
					this.OnHaber_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OkunmaSayisi", DbType="Int")]
		public System.Nullable<int> OkunmaSayisi
		{
			get
			{
				return this._OkunmaSayisi;
			}
			set
			{
				if ((this._OkunmaSayisi != value))
				{
					this.OnOkunmaSayisiChanging(value);
					this.SendPropertyChanging();
					this._OkunmaSayisi = value;
					this.SendPropertyChanged("OkunmaSayisi");
					this.OnOkunmaSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Icerik_tbl_PortalHaber_OkunmaSayisi", Storage="_tbl_PortalHaber_Icerik", ThisKey="Haber_ID", OtherKey="HaberId", IsForeignKey=true)]
		public tbl_PortalHaber_Icerik tbl_PortalHaber_Icerik
		{
			get
			{
				return this._tbl_PortalHaber_Icerik.Entity;
			}
			set
			{
				tbl_PortalHaber_Icerik previousValue = this._tbl_PortalHaber_Icerik.Entity;
				if (((previousValue != value) 
							|| (this._tbl_PortalHaber_Icerik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_PortalHaber_Icerik.Entity = null;
						previousValue.tbl_PortalHaber_OkunmaSayisis.Remove(this);
					}
					this._tbl_PortalHaber_Icerik.Entity = value;
					if ((value != null))
					{
						value.tbl_PortalHaber_OkunmaSayisis.Add(this);
						this._Haber_ID = value.HaberId;
					}
					else
					{
						this._Haber_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_PortalHaber_Icerik");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PortalHaber_Site")]
	public partial class tbl_PortalHaber_Site : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Site_Id;
		
		private string _Site_Adi;
		
		private System.Nullable<int> _Site_Grubu;
		
		private EntitySet<tbl_PortalHaber_YazarSiteRelation> _tbl_PortalHaber_YazarSiteRelations;
		
		private EntitySet<tbl_PortalHaber_Icerik> _tbl_PortalHaber_Iceriks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSite_IdChanging(int value);
    partial void OnSite_IdChanged();
    partial void OnSite_AdiChanging(string value);
    partial void OnSite_AdiChanged();
    partial void OnSite_GrubuChanging(System.Nullable<int> value);
    partial void OnSite_GrubuChanged();
    #endregion
		
		public tbl_PortalHaber_Site()
		{
			this._tbl_PortalHaber_YazarSiteRelations = new EntitySet<tbl_PortalHaber_YazarSiteRelation>(new Action<tbl_PortalHaber_YazarSiteRelation>(this.attach_tbl_PortalHaber_YazarSiteRelations), new Action<tbl_PortalHaber_YazarSiteRelation>(this.detach_tbl_PortalHaber_YazarSiteRelations));
			this._tbl_PortalHaber_Iceriks = new EntitySet<tbl_PortalHaber_Icerik>(new Action<tbl_PortalHaber_Icerik>(this.attach_tbl_PortalHaber_Iceriks), new Action<tbl_PortalHaber_Icerik>(this.detach_tbl_PortalHaber_Iceriks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Site_Id
		{
			get
			{
				return this._Site_Id;
			}
			set
			{
				if ((this._Site_Id != value))
				{
					this.OnSite_IdChanging(value);
					this.SendPropertyChanging();
					this._Site_Id = value;
					this.SendPropertyChanged("Site_Id");
					this.OnSite_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_Adi", DbType="VarChar(50)")]
		public string Site_Adi
		{
			get
			{
				return this._Site_Adi;
			}
			set
			{
				if ((this._Site_Adi != value))
				{
					this.OnSite_AdiChanging(value);
					this.SendPropertyChanging();
					this._Site_Adi = value;
					this.SendPropertyChanged("Site_Adi");
					this.OnSite_AdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_Grubu", DbType="Int")]
		public System.Nullable<int> Site_Grubu
		{
			get
			{
				return this._Site_Grubu;
			}
			set
			{
				if ((this._Site_Grubu != value))
				{
					this.OnSite_GrubuChanging(value);
					this.SendPropertyChanging();
					this._Site_Grubu = value;
					this.SendPropertyChanged("Site_Grubu");
					this.OnSite_GrubuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Site_tbl_PortalHaber_YazarSiteRelation", Storage="_tbl_PortalHaber_YazarSiteRelations", ThisKey="Site_Id", OtherKey="SiteId")]
		public EntitySet<tbl_PortalHaber_YazarSiteRelation> tbl_PortalHaber_YazarSiteRelations
		{
			get
			{
				return this._tbl_PortalHaber_YazarSiteRelations;
			}
			set
			{
				this._tbl_PortalHaber_YazarSiteRelations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Site_tbl_PortalHaber_Icerik", Storage="_tbl_PortalHaber_Iceriks", ThisKey="Site_Id", OtherKey="Site_Id")]
		public EntitySet<tbl_PortalHaber_Icerik> tbl_PortalHaber_Iceriks
		{
			get
			{
				return this._tbl_PortalHaber_Iceriks;
			}
			set
			{
				this._tbl_PortalHaber_Iceriks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PortalHaber_YazarSiteRelations(tbl_PortalHaber_YazarSiteRelation entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Site = this;
		}
		
		private void detach_tbl_PortalHaber_YazarSiteRelations(tbl_PortalHaber_YazarSiteRelation entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Site = null;
		}
		
		private void attach_tbl_PortalHaber_Iceriks(tbl_PortalHaber_Icerik entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Site = this;
		}
		
		private void detach_tbl_PortalHaber_Iceriks(tbl_PortalHaber_Icerik entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Site = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PortalHaber_Tip")]
	public partial class tbl_PortalHaber_Tip : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Tip_Id;
		
		private string _Tip_Adi;
		
		private EntitySet<tbl_PortalHaber_Yazar> _tbl_PortalHaber_Yazars;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTip_IdChanging(int value);
    partial void OnTip_IdChanged();
    partial void OnTip_AdiChanging(string value);
    partial void OnTip_AdiChanged();
    #endregion
		
		public tbl_PortalHaber_Tip()
		{
			this._tbl_PortalHaber_Yazars = new EntitySet<tbl_PortalHaber_Yazar>(new Action<tbl_PortalHaber_Yazar>(this.attach_tbl_PortalHaber_Yazars), new Action<tbl_PortalHaber_Yazar>(this.detach_tbl_PortalHaber_Yazars));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tip_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Tip_Id
		{
			get
			{
				return this._Tip_Id;
			}
			set
			{
				if ((this._Tip_Id != value))
				{
					this.OnTip_IdChanging(value);
					this.SendPropertyChanging();
					this._Tip_Id = value;
					this.SendPropertyChanged("Tip_Id");
					this.OnTip_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tip_Adi", DbType="VarChar(50)")]
		public string Tip_Adi
		{
			get
			{
				return this._Tip_Adi;
			}
			set
			{
				if ((this._Tip_Adi != value))
				{
					this.OnTip_AdiChanging(value);
					this.SendPropertyChanging();
					this._Tip_Adi = value;
					this.SendPropertyChanged("Tip_Adi");
					this.OnTip_AdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Tip_tbl_PortalHaber_Yazar", Storage="_tbl_PortalHaber_Yazars", ThisKey="Tip_Id", OtherKey="Tipi")]
		public EntitySet<tbl_PortalHaber_Yazar> tbl_PortalHaber_Yazars
		{
			get
			{
				return this._tbl_PortalHaber_Yazars;
			}
			set
			{
				this._tbl_PortalHaber_Yazars.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PortalHaber_Yazars(tbl_PortalHaber_Yazar entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Tip = this;
		}
		
		private void detach_tbl_PortalHaber_Yazars(tbl_PortalHaber_Yazar entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Tip = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PortalHaber_Yazar")]
	public partial class tbl_PortalHaber_Yazar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _YazarId;
		
		private string _YName;
		
		private System.Nullable<int> _Tipi;
		
		private string _Sifre;
		
		private string _EPosta;
		
		private string _Resim;
		
		private EntitySet<tbl_PortalHaber_YazarSiteRelation> _tbl_PortalHaber_YazarSiteRelations;
		
		private EntityRef<tbl_PortalHaber_Tip> _tbl_PortalHaber_Tip;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYazarIdChanging(int value);
    partial void OnYazarIdChanged();
    partial void OnYNameChanging(string value);
    partial void OnYNameChanged();
    partial void OnTipiChanging(System.Nullable<int> value);
    partial void OnTipiChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    partial void OnEPostaChanging(string value);
    partial void OnEPostaChanged();
    partial void OnResimChanging(string value);
    partial void OnResimChanged();
    #endregion
		
		public tbl_PortalHaber_Yazar()
		{
			this._tbl_PortalHaber_YazarSiteRelations = new EntitySet<tbl_PortalHaber_YazarSiteRelation>(new Action<tbl_PortalHaber_YazarSiteRelation>(this.attach_tbl_PortalHaber_YazarSiteRelations), new Action<tbl_PortalHaber_YazarSiteRelation>(this.detach_tbl_PortalHaber_YazarSiteRelations));
			this._tbl_PortalHaber_Tip = default(EntityRef<tbl_PortalHaber_Tip>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YazarId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int YazarId
		{
			get
			{
				return this._YazarId;
			}
			set
			{
				if ((this._YazarId != value))
				{
					this.OnYazarIdChanging(value);
					this.SendPropertyChanging();
					this._YazarId = value;
					this.SendPropertyChanged("YazarId");
					this.OnYazarIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YName", DbType="VarChar(255)")]
		public string YName
		{
			get
			{
				return this._YName;
			}
			set
			{
				if ((this._YName != value))
				{
					this.OnYNameChanging(value);
					this.SendPropertyChanging();
					this._YName = value;
					this.SendPropertyChanged("YName");
					this.OnYNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipi", DbType="Int")]
		public System.Nullable<int> Tipi
		{
			get
			{
				return this._Tipi;
			}
			set
			{
				if ((this._Tipi != value))
				{
					if (this._tbl_PortalHaber_Tip.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTipiChanging(value);
					this.SendPropertyChanging();
					this._Tipi = value;
					this.SendPropertyChanged("Tipi");
					this.OnTipiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="VarChar(50)")]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPosta", DbType="VarChar(50)")]
		public string EPosta
		{
			get
			{
				return this._EPosta;
			}
			set
			{
				if ((this._EPosta != value))
				{
					this.OnEPostaChanging(value);
					this.SendPropertyChanging();
					this._EPosta = value;
					this.SendPropertyChanged("EPosta");
					this.OnEPostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="VarChar(255)")]
		public string Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this.OnResimChanging(value);
					this.SendPropertyChanging();
					this._Resim = value;
					this.SendPropertyChanged("Resim");
					this.OnResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Yazar_tbl_PortalHaber_YazarSiteRelation", Storage="_tbl_PortalHaber_YazarSiteRelations", ThisKey="YazarId", OtherKey="YazarId")]
		public EntitySet<tbl_PortalHaber_YazarSiteRelation> tbl_PortalHaber_YazarSiteRelations
		{
			get
			{
				return this._tbl_PortalHaber_YazarSiteRelations;
			}
			set
			{
				this._tbl_PortalHaber_YazarSiteRelations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Tip_tbl_PortalHaber_Yazar", Storage="_tbl_PortalHaber_Tip", ThisKey="Tipi", OtherKey="Tip_Id", IsForeignKey=true)]
		public tbl_PortalHaber_Tip tbl_PortalHaber_Tip
		{
			get
			{
				return this._tbl_PortalHaber_Tip.Entity;
			}
			set
			{
				tbl_PortalHaber_Tip previousValue = this._tbl_PortalHaber_Tip.Entity;
				if (((previousValue != value) 
							|| (this._tbl_PortalHaber_Tip.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_PortalHaber_Tip.Entity = null;
						previousValue.tbl_PortalHaber_Yazars.Remove(this);
					}
					this._tbl_PortalHaber_Tip.Entity = value;
					if ((value != null))
					{
						value.tbl_PortalHaber_Yazars.Add(this);
						this._Tipi = value.Tip_Id;
					}
					else
					{
						this._Tipi = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_PortalHaber_Tip");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PortalHaber_YazarSiteRelations(tbl_PortalHaber_YazarSiteRelation entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Yazar = this;
		}
		
		private void detach_tbl_PortalHaber_YazarSiteRelations(tbl_PortalHaber_YazarSiteRelation entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Yazar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PortalHaber_YazarSiteRelation")]
	public partial class tbl_PortalHaber_YazarSiteRelation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _YazarId;
		
		private System.Nullable<int> _SiteId;
		
		private EntityRef<tbl_PortalHaber_Site> _tbl_PortalHaber_Site;
		
		private EntityRef<tbl_PortalHaber_Yazar> _tbl_PortalHaber_Yazar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnYazarIdChanging(System.Nullable<int> value);
    partial void OnYazarIdChanged();
    partial void OnSiteIdChanging(System.Nullable<int> value);
    partial void OnSiteIdChanged();
    #endregion
		
		public tbl_PortalHaber_YazarSiteRelation()
		{
			this._tbl_PortalHaber_Site = default(EntityRef<tbl_PortalHaber_Site>);
			this._tbl_PortalHaber_Yazar = default(EntityRef<tbl_PortalHaber_Yazar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YazarId", DbType="Int")]
		public System.Nullable<int> YazarId
		{
			get
			{
				return this._YazarId;
			}
			set
			{
				if ((this._YazarId != value))
				{
					if (this._tbl_PortalHaber_Yazar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnYazarIdChanging(value);
					this.SendPropertyChanging();
					this._YazarId = value;
					this.SendPropertyChanged("YazarId");
					this.OnYazarIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteId", DbType="Int")]
		public System.Nullable<int> SiteId
		{
			get
			{
				return this._SiteId;
			}
			set
			{
				if ((this._SiteId != value))
				{
					if (this._tbl_PortalHaber_Site.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSiteIdChanging(value);
					this.SendPropertyChanging();
					this._SiteId = value;
					this.SendPropertyChanged("SiteId");
					this.OnSiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Site_tbl_PortalHaber_YazarSiteRelation", Storage="_tbl_PortalHaber_Site", ThisKey="SiteId", OtherKey="Site_Id", IsForeignKey=true)]
		public tbl_PortalHaber_Site tbl_PortalHaber_Site
		{
			get
			{
				return this._tbl_PortalHaber_Site.Entity;
			}
			set
			{
				tbl_PortalHaber_Site previousValue = this._tbl_PortalHaber_Site.Entity;
				if (((previousValue != value) 
							|| (this._tbl_PortalHaber_Site.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_PortalHaber_Site.Entity = null;
						previousValue.tbl_PortalHaber_YazarSiteRelations.Remove(this);
					}
					this._tbl_PortalHaber_Site.Entity = value;
					if ((value != null))
					{
						value.tbl_PortalHaber_YazarSiteRelations.Add(this);
						this._SiteId = value.Site_Id;
					}
					else
					{
						this._SiteId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_PortalHaber_Site");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Yazar_tbl_PortalHaber_YazarSiteRelation", Storage="_tbl_PortalHaber_Yazar", ThisKey="YazarId", OtherKey="YazarId", IsForeignKey=true)]
		public tbl_PortalHaber_Yazar tbl_PortalHaber_Yazar
		{
			get
			{
				return this._tbl_PortalHaber_Yazar.Entity;
			}
			set
			{
				tbl_PortalHaber_Yazar previousValue = this._tbl_PortalHaber_Yazar.Entity;
				if (((previousValue != value) 
							|| (this._tbl_PortalHaber_Yazar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_PortalHaber_Yazar.Entity = null;
						previousValue.tbl_PortalHaber_YazarSiteRelations.Remove(this);
					}
					this._tbl_PortalHaber_Yazar.Entity = value;
					if ((value != null))
					{
						value.tbl_PortalHaber_YazarSiteRelations.Add(this);
						this._YazarId = value.YazarId;
					}
					else
					{
						this._YazarId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_PortalHaber_Yazar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PortalHaber_Kaynak")]
	public partial class tbl_PortalHaber_Kaynak : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KaynakId;
		
		private string _Adi;
		
		private EntitySet<tbl_PortalHaber_Icerik> _tbl_PortalHaber_Iceriks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKaynakIdChanging(int value);
    partial void OnKaynakIdChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    #endregion
		
		public tbl_PortalHaber_Kaynak()
		{
			this._tbl_PortalHaber_Iceriks = new EntitySet<tbl_PortalHaber_Icerik>(new Action<tbl_PortalHaber_Icerik>(this.attach_tbl_PortalHaber_Iceriks), new Action<tbl_PortalHaber_Icerik>(this.detach_tbl_PortalHaber_Iceriks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KaynakId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int KaynakId
		{
			get
			{
				return this._KaynakId;
			}
			set
			{
				if ((this._KaynakId != value))
				{
					this.OnKaynakIdChanging(value);
					this.SendPropertyChanging();
					this._KaynakId = value;
					this.SendPropertyChanged("KaynakId");
					this.OnKaynakIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="VarChar(50)")]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Kaynak_tbl_PortalHaber_Icerik", Storage="_tbl_PortalHaber_Iceriks", ThisKey="KaynakId", OtherKey="KaynakId")]
		public EntitySet<tbl_PortalHaber_Icerik> tbl_PortalHaber_Iceriks
		{
			get
			{
				return this._tbl_PortalHaber_Iceriks;
			}
			set
			{
				this._tbl_PortalHaber_Iceriks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PortalHaber_Iceriks(tbl_PortalHaber_Icerik entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Kaynak = this;
		}
		
		private void detach_tbl_PortalHaber_Iceriks(tbl_PortalHaber_Icerik entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Kaynak = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VWBANNER")]
	public partial class VWBANNER
	{
		
		private int _SbId;
		
		private string _SiteAdi;
		
		private string _BannerAdi;
		
		private System.Nullable<int> _BannerAdet;
		
		public VWBANNER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SbId", DbType="Int NOT NULL")]
		public int SbId
		{
			get
			{
				return this._SbId;
			}
			set
			{
				if ((this._SbId != value))
				{
					this._SbId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteAdi", DbType="VarChar(50)")]
		public string SiteAdi
		{
			get
			{
				return this._SiteAdi;
			}
			set
			{
				if ((this._SiteAdi != value))
				{
					this._SiteAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BannerAdi", DbType="VarChar(255)")]
		public string BannerAdi
		{
			get
			{
				return this._BannerAdi;
			}
			set
			{
				if ((this._BannerAdi != value))
				{
					this._BannerAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BannerAdet", DbType="Int")]
		public System.Nullable<int> BannerAdet
		{
			get
			{
				return this._BannerAdet;
			}
			set
			{
				if ((this._BannerAdet != value))
				{
					this._BannerAdet = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PortalHaber_Icerik")]
	public partial class tbl_PortalHaber_Icerik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HaberId;
		
		private string _HaberBaslik;
		
		private string _HaberAciklama;
		
		private System.Nullable<int> _KategoriId;
		
		private string _HaberUrl;
		
		private System.Nullable<int> _KaynakId;
		
		private System.Nullable<int> _Site_Id;
		
		private System.Nullable<System.DateTime> _Onay_Tarih;
		
		private string _Haber_Resim;
		
		private System.Nullable<bool> _Onay;
		
		private System.Nullable<int> _Banner_Tip;
		
		private EntitySet<tbl_PortalHaber_IP> _tbl_PortalHaber_IPs;
		
		private EntitySet<tbl_PortalHaber_OkunmaSayisi> _tbl_PortalHaber_OkunmaSayisis;
		
		private EntitySet<tbl_PortalHaber_Icerik2> _tbl_PortalHaber_Icerik2s;
		
		private EntityRef<tbl_PortalHaber_kategori> _tbl_PortalHaber_kategori;
		
		private EntityRef<tbl_PortalHaber_Kaynak> _tbl_PortalHaber_Kaynak;
		
		private EntityRef<tbl_PortalHaber_Site> _tbl_PortalHaber_Site;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHaberIdChanging(int value);
    partial void OnHaberIdChanged();
    partial void OnHaberBaslikChanging(string value);
    partial void OnHaberBaslikChanged();
    partial void OnHaberAciklamaChanging(string value);
    partial void OnHaberAciklamaChanged();
    partial void OnKategoriIdChanging(System.Nullable<int> value);
    partial void OnKategoriIdChanged();
    partial void OnHaberUrlChanging(string value);
    partial void OnHaberUrlChanged();
    partial void OnKaynakIdChanging(System.Nullable<int> value);
    partial void OnKaynakIdChanged();
    partial void OnSite_IdChanging(System.Nullable<int> value);
    partial void OnSite_IdChanged();
    partial void OnOnay_TarihChanging(System.Nullable<System.DateTime> value);
    partial void OnOnay_TarihChanged();
    partial void OnHaber_ResimChanging(string value);
    partial void OnHaber_ResimChanged();
    partial void OnOnayChanging(System.Nullable<bool> value);
    partial void OnOnayChanged();
    partial void OnBanner_TipChanging(System.Nullable<int> value);
    partial void OnBanner_TipChanged();
    #endregion
		
		public tbl_PortalHaber_Icerik()
		{
			this._tbl_PortalHaber_IPs = new EntitySet<tbl_PortalHaber_IP>(new Action<tbl_PortalHaber_IP>(this.attach_tbl_PortalHaber_IPs), new Action<tbl_PortalHaber_IP>(this.detach_tbl_PortalHaber_IPs));
			this._tbl_PortalHaber_OkunmaSayisis = new EntitySet<tbl_PortalHaber_OkunmaSayisi>(new Action<tbl_PortalHaber_OkunmaSayisi>(this.attach_tbl_PortalHaber_OkunmaSayisis), new Action<tbl_PortalHaber_OkunmaSayisi>(this.detach_tbl_PortalHaber_OkunmaSayisis));
			this._tbl_PortalHaber_Icerik2s = new EntitySet<tbl_PortalHaber_Icerik2>(new Action<tbl_PortalHaber_Icerik2>(this.attach_tbl_PortalHaber_Icerik2s), new Action<tbl_PortalHaber_Icerik2>(this.detach_tbl_PortalHaber_Icerik2s));
			this._tbl_PortalHaber_kategori = default(EntityRef<tbl_PortalHaber_kategori>);
			this._tbl_PortalHaber_Kaynak = default(EntityRef<tbl_PortalHaber_Kaynak>);
			this._tbl_PortalHaber_Site = default(EntityRef<tbl_PortalHaber_Site>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaberId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HaberId
		{
			get
			{
				return this._HaberId;
			}
			set
			{
				if ((this._HaberId != value))
				{
					this.OnHaberIdChanging(value);
					this.SendPropertyChanging();
					this._HaberId = value;
					this.SendPropertyChanged("HaberId");
					this.OnHaberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaberBaslik", DbType="VarChar(255)")]
		public string HaberBaslik
		{
			get
			{
				return this._HaberBaslik;
			}
			set
			{
				if ((this._HaberBaslik != value))
				{
					this.OnHaberBaslikChanging(value);
					this.SendPropertyChanging();
					this._HaberBaslik = value;
					this.SendPropertyChanged("HaberBaslik");
					this.OnHaberBaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaberAciklama", DbType="VarChar(MAX)")]
		public string HaberAciklama
		{
			get
			{
				return this._HaberAciklama;
			}
			set
			{
				if ((this._HaberAciklama != value))
				{
					this.OnHaberAciklamaChanging(value);
					this.SendPropertyChanging();
					this._HaberAciklama = value;
					this.SendPropertyChanged("HaberAciklama");
					this.OnHaberAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriId", DbType="Int")]
		public System.Nullable<int> KategoriId
		{
			get
			{
				return this._KategoriId;
			}
			set
			{
				if ((this._KategoriId != value))
				{
					if (this._tbl_PortalHaber_kategori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKategoriIdChanging(value);
					this.SendPropertyChanging();
					this._KategoriId = value;
					this.SendPropertyChanged("KategoriId");
					this.OnKategoriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaberUrl", DbType="VarChar(50)")]
		public string HaberUrl
		{
			get
			{
				return this._HaberUrl;
			}
			set
			{
				if ((this._HaberUrl != value))
				{
					this.OnHaberUrlChanging(value);
					this.SendPropertyChanging();
					this._HaberUrl = value;
					this.SendPropertyChanged("HaberUrl");
					this.OnHaberUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KaynakId", DbType="Int")]
		public System.Nullable<int> KaynakId
		{
			get
			{
				return this._KaynakId;
			}
			set
			{
				if ((this._KaynakId != value))
				{
					if (this._tbl_PortalHaber_Kaynak.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKaynakIdChanging(value);
					this.SendPropertyChanging();
					this._KaynakId = value;
					this.SendPropertyChanged("KaynakId");
					this.OnKaynakIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_Id", DbType="Int")]
		public System.Nullable<int> Site_Id
		{
			get
			{
				return this._Site_Id;
			}
			set
			{
				if ((this._Site_Id != value))
				{
					if (this._tbl_PortalHaber_Site.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSite_IdChanging(value);
					this.SendPropertyChanging();
					this._Site_Id = value;
					this.SendPropertyChanged("Site_Id");
					this.OnSite_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Onay_Tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> Onay_Tarih
		{
			get
			{
				return this._Onay_Tarih;
			}
			set
			{
				if ((this._Onay_Tarih != value))
				{
					this.OnOnay_TarihChanging(value);
					this.SendPropertyChanging();
					this._Onay_Tarih = value;
					this.SendPropertyChanged("Onay_Tarih");
					this.OnOnay_TarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Haber_Resim", DbType="VarChar(MAX)")]
		public string Haber_Resim
		{
			get
			{
				return this._Haber_Resim;
			}
			set
			{
				if ((this._Haber_Resim != value))
				{
					this.OnHaber_ResimChanging(value);
					this.SendPropertyChanging();
					this._Haber_Resim = value;
					this.SendPropertyChanged("Haber_Resim");
					this.OnHaber_ResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Onay", DbType="Bit")]
		public System.Nullable<bool> Onay
		{
			get
			{
				return this._Onay;
			}
			set
			{
				if ((this._Onay != value))
				{
					this.OnOnayChanging(value);
					this.SendPropertyChanging();
					this._Onay = value;
					this.SendPropertyChanged("Onay");
					this.OnOnayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Banner_Tip", DbType="Int")]
		public System.Nullable<int> Banner_Tip
		{
			get
			{
				return this._Banner_Tip;
			}
			set
			{
				if ((this._Banner_Tip != value))
				{
					this.OnBanner_TipChanging(value);
					this.SendPropertyChanging();
					this._Banner_Tip = value;
					this.SendPropertyChanged("Banner_Tip");
					this.OnBanner_TipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Icerik_tbl_PortalHaber_IP", Storage="_tbl_PortalHaber_IPs", ThisKey="HaberId", OtherKey="Haber_Id")]
		public EntitySet<tbl_PortalHaber_IP> tbl_PortalHaber_IPs
		{
			get
			{
				return this._tbl_PortalHaber_IPs;
			}
			set
			{
				this._tbl_PortalHaber_IPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Icerik_tbl_PortalHaber_OkunmaSayisi", Storage="_tbl_PortalHaber_OkunmaSayisis", ThisKey="HaberId", OtherKey="Haber_ID")]
		public EntitySet<tbl_PortalHaber_OkunmaSayisi> tbl_PortalHaber_OkunmaSayisis
		{
			get
			{
				return this._tbl_PortalHaber_OkunmaSayisis;
			}
			set
			{
				this._tbl_PortalHaber_OkunmaSayisis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Icerik_tbl_PortalHaber_Icerik2", Storage="_tbl_PortalHaber_Icerik2s", ThisKey="HaberId", OtherKey="HaberId")]
		public EntitySet<tbl_PortalHaber_Icerik2> tbl_PortalHaber_Icerik2s
		{
			get
			{
				return this._tbl_PortalHaber_Icerik2s;
			}
			set
			{
				this._tbl_PortalHaber_Icerik2s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_kategori_tbl_PortalHaber_Icerik", Storage="_tbl_PortalHaber_kategori", ThisKey="KategoriId", OtherKey="Kid", IsForeignKey=true)]
		public tbl_PortalHaber_kategori tbl_PortalHaber_kategori
		{
			get
			{
				return this._tbl_PortalHaber_kategori.Entity;
			}
			set
			{
				tbl_PortalHaber_kategori previousValue = this._tbl_PortalHaber_kategori.Entity;
				if (((previousValue != value) 
							|| (this._tbl_PortalHaber_kategori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_PortalHaber_kategori.Entity = null;
						previousValue.tbl_PortalHaber_Iceriks.Remove(this);
					}
					this._tbl_PortalHaber_kategori.Entity = value;
					if ((value != null))
					{
						value.tbl_PortalHaber_Iceriks.Add(this);
						this._KategoriId = value.Kid;
					}
					else
					{
						this._KategoriId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_PortalHaber_kategori");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Kaynak_tbl_PortalHaber_Icerik", Storage="_tbl_PortalHaber_Kaynak", ThisKey="KaynakId", OtherKey="KaynakId", IsForeignKey=true)]
		public tbl_PortalHaber_Kaynak tbl_PortalHaber_Kaynak
		{
			get
			{
				return this._tbl_PortalHaber_Kaynak.Entity;
			}
			set
			{
				tbl_PortalHaber_Kaynak previousValue = this._tbl_PortalHaber_Kaynak.Entity;
				if (((previousValue != value) 
							|| (this._tbl_PortalHaber_Kaynak.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_PortalHaber_Kaynak.Entity = null;
						previousValue.tbl_PortalHaber_Iceriks.Remove(this);
					}
					this._tbl_PortalHaber_Kaynak.Entity = value;
					if ((value != null))
					{
						value.tbl_PortalHaber_Iceriks.Add(this);
						this._KaynakId = value.KaynakId;
					}
					else
					{
						this._KaynakId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_PortalHaber_Kaynak");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Site_tbl_PortalHaber_Icerik", Storage="_tbl_PortalHaber_Site", ThisKey="Site_Id", OtherKey="Site_Id", IsForeignKey=true)]
		public tbl_PortalHaber_Site tbl_PortalHaber_Site
		{
			get
			{
				return this._tbl_PortalHaber_Site.Entity;
			}
			set
			{
				tbl_PortalHaber_Site previousValue = this._tbl_PortalHaber_Site.Entity;
				if (((previousValue != value) 
							|| (this._tbl_PortalHaber_Site.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_PortalHaber_Site.Entity = null;
						previousValue.tbl_PortalHaber_Iceriks.Remove(this);
					}
					this._tbl_PortalHaber_Site.Entity = value;
					if ((value != null))
					{
						value.tbl_PortalHaber_Iceriks.Add(this);
						this._Site_Id = value.Site_Id;
					}
					else
					{
						this._Site_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_PortalHaber_Site");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PortalHaber_IPs(tbl_PortalHaber_IP entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Icerik = this;
		}
		
		private void detach_tbl_PortalHaber_IPs(tbl_PortalHaber_IP entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Icerik = null;
		}
		
		private void attach_tbl_PortalHaber_OkunmaSayisis(tbl_PortalHaber_OkunmaSayisi entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Icerik = this;
		}
		
		private void detach_tbl_PortalHaber_OkunmaSayisis(tbl_PortalHaber_OkunmaSayisi entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Icerik = null;
		}
		
		private void attach_tbl_PortalHaber_Icerik2s(tbl_PortalHaber_Icerik2 entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Icerik = this;
		}
		
		private void detach_tbl_PortalHaber_Icerik2s(tbl_PortalHaber_Icerik2 entity)
		{
			this.SendPropertyChanging();
			entity.tbl_PortalHaber_Icerik = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PortalHaber_Icerik2")]
	public partial class tbl_PortalHaber_Icerik2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HDid;
		
		private string _HaberMetni;
		
		private string _Etiketler;
		
		private System.Nullable<int> _YazarId;
		
		private System.Nullable<int> _HaberId;
		
		private EntityRef<tbl_PortalHaber_Icerik> _tbl_PortalHaber_Icerik;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHDidChanging(int value);
    partial void OnHDidChanged();
    partial void OnHaberMetniChanging(string value);
    partial void OnHaberMetniChanged();
    partial void OnEtiketlerChanging(string value);
    partial void OnEtiketlerChanged();
    partial void OnYazarIdChanging(System.Nullable<int> value);
    partial void OnYazarIdChanged();
    partial void OnHaberIdChanging(System.Nullable<int> value);
    partial void OnHaberIdChanged();
    #endregion
		
		public tbl_PortalHaber_Icerik2()
		{
			this._tbl_PortalHaber_Icerik = default(EntityRef<tbl_PortalHaber_Icerik>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HDid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HDid
		{
			get
			{
				return this._HDid;
			}
			set
			{
				if ((this._HDid != value))
				{
					this.OnHDidChanging(value);
					this.SendPropertyChanging();
					this._HDid = value;
					this.SendPropertyChanged("HDid");
					this.OnHDidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaberMetni", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string HaberMetni
		{
			get
			{
				return this._HaberMetni;
			}
			set
			{
				if ((this._HaberMetni != value))
				{
					this.OnHaberMetniChanging(value);
					this.SendPropertyChanging();
					this._HaberMetni = value;
					this.SendPropertyChanged("HaberMetni");
					this.OnHaberMetniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiketler", DbType="VarChar(MAX)")]
		public string Etiketler
		{
			get
			{
				return this._Etiketler;
			}
			set
			{
				if ((this._Etiketler != value))
				{
					this.OnEtiketlerChanging(value);
					this.SendPropertyChanging();
					this._Etiketler = value;
					this.SendPropertyChanged("Etiketler");
					this.OnEtiketlerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YazarId", DbType="Int")]
		public System.Nullable<int> YazarId
		{
			get
			{
				return this._YazarId;
			}
			set
			{
				if ((this._YazarId != value))
				{
					this.OnYazarIdChanging(value);
					this.SendPropertyChanging();
					this._YazarId = value;
					this.SendPropertyChanged("YazarId");
					this.OnYazarIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaberId", DbType="Int")]
		public System.Nullable<int> HaberId
		{
			get
			{
				return this._HaberId;
			}
			set
			{
				if ((this._HaberId != value))
				{
					if (this._tbl_PortalHaber_Icerik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHaberIdChanging(value);
					this.SendPropertyChanging();
					this._HaberId = value;
					this.SendPropertyChanged("HaberId");
					this.OnHaberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_PortalHaber_Icerik_tbl_PortalHaber_Icerik2", Storage="_tbl_PortalHaber_Icerik", ThisKey="HaberId", OtherKey="HaberId", IsForeignKey=true)]
		public tbl_PortalHaber_Icerik tbl_PortalHaber_Icerik
		{
			get
			{
				return this._tbl_PortalHaber_Icerik.Entity;
			}
			set
			{
				tbl_PortalHaber_Icerik previousValue = this._tbl_PortalHaber_Icerik.Entity;
				if (((previousValue != value) 
							|| (this._tbl_PortalHaber_Icerik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_PortalHaber_Icerik.Entity = null;
						previousValue.tbl_PortalHaber_Icerik2s.Remove(this);
					}
					this._tbl_PortalHaber_Icerik.Entity = value;
					if ((value != null))
					{
						value.tbl_PortalHaber_Icerik2s.Add(this);
						this._HaberId = value.HaberId;
					}
					else
					{
						this._HaberId = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_PortalHaber_Icerik");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VWYHABERLIST")]
	public partial class VWYHABERLIST
	{
		
		private int _id;
		
		private string _EPosta;
		
		private string _HaberBaslik;
		
		private string _HaberAciklama;
		
		public VWYHABERLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPosta", DbType="VarChar(50)")]
		public string EPosta
		{
			get
			{
				return this._EPosta;
			}
			set
			{
				if ((this._EPosta != value))
				{
					this._EPosta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaberBaslik", DbType="VarChar(255)")]
		public string HaberBaslik
		{
			get
			{
				return this._HaberBaslik;
			}
			set
			{
				if ((this._HaberBaslik != value))
				{
					this._HaberBaslik = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaberAciklama", DbType="VarChar(MAX)")]
		public string HaberAciklama
		{
			get
			{
				return this._HaberAciklama;
			}
			set
			{
				if ((this._HaberAciklama != value))
				{
					this._HaberAciklama = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
