<?xml version="1.0" encoding="utf-8"?><Database Name="DB090928093827" Class="ManageDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=89.19.29.204;Initial Catalog=DB090928093827;Persist Security Info=True;User ID=USR090928093827" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB090928093827ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_PortalHaber_IP" Member="tbl_PortalHaber_IPs">
    <Type Name="tbl_PortalHaber_IP">
      <Column Name="IP_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Haber_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="tbl_PortalHaber_Icerik_tbl_PortalHaber_IP" Member="tbl_PortalHaber_Icerik" ThisKey="Haber_Id" OtherKey="HaberId" Type="tbl_PortalHaber_Icerik" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PortalHaber_kategori" Member="tbl_PortalHaber_kategoris">
    <Type Name="tbl_PortalHaber_kategori">
      <Column Name="Kid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="tbl_PortalHaber_kategori_tbl_PortalHaber_Icerik" Member="tbl_PortalHaber_Iceriks" ThisKey="Kid" OtherKey="KategoriId" Type="tbl_PortalHaber_Icerik" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PortalHaber_OkunmaSayisi" Member="tbl_PortalHaber_OkunmaSayisis">
    <Type Name="tbl_PortalHaber_OkunmaSayisi">
      <Column Name="OS_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Haber_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OkunmaSayisi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_PortalHaber_Icerik_tbl_PortalHaber_OkunmaSayisi" Member="tbl_PortalHaber_Icerik" ThisKey="Haber_ID" OtherKey="HaberId" Type="tbl_PortalHaber_Icerik" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PortalHaber_Site" Member="tbl_PortalHaber_Sites">
    <Type Name="tbl_PortalHaber_Site">
      <Column Name="Site_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Site_Adi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Site_Grubu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_PortalHaber_Site_tbl_PortalHaber_YazarSiteRelation" Member="tbl_PortalHaber_YazarSiteRelations" ThisKey="Site_Id" OtherKey="SiteId" Type="tbl_PortalHaber_YazarSiteRelation" />
      <Association Name="tbl_PortalHaber_Site_tbl_PortalHaber_Icerik" Member="tbl_PortalHaber_Iceriks" ThisKey="Site_Id" OtherKey="Site_Id" Type="tbl_PortalHaber_Icerik" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PortalHaber_Tip" Member="tbl_PortalHaber_Tips">
    <Type Name="tbl_PortalHaber_Tip">
      <Column Name="Tip_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tip_Adi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tbl_PortalHaber_Tip_tbl_PortalHaber_Yazar" Member="tbl_PortalHaber_Yazars" ThisKey="Tip_Id" OtherKey="Tipi" Type="tbl_PortalHaber_Yazar" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PortalHaber_Yazar" Member="tbl_PortalHaber_Yazars">
    <Type Name="tbl_PortalHaber_Yazar">
      <Column Name="YazarId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="YName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Tipi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sifre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EPosta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Resim" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="tbl_PortalHaber_Yazar_tbl_PortalHaber_YazarSiteRelation" Member="tbl_PortalHaber_YazarSiteRelations" ThisKey="YazarId" OtherKey="YazarId" Type="tbl_PortalHaber_YazarSiteRelation" />
      <Association Name="tbl_PortalHaber_Tip_tbl_PortalHaber_Yazar" Member="tbl_PortalHaber_Tip" ThisKey="Tipi" OtherKey="Tip_Id" Type="tbl_PortalHaber_Tip" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PortalHaber_YazarSiteRelation" Member="tbl_PortalHaber_YazarSiteRelations">
    <Type Name="tbl_PortalHaber_YazarSiteRelation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="YazarId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SiteId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_PortalHaber_Site_tbl_PortalHaber_YazarSiteRelation" Member="tbl_PortalHaber_Site" ThisKey="SiteId" OtherKey="Site_Id" Type="tbl_PortalHaber_Site" IsForeignKey="true" />
      <Association Name="tbl_PortalHaber_Yazar_tbl_PortalHaber_YazarSiteRelation" Member="tbl_PortalHaber_Yazar" ThisKey="YazarId" OtherKey="YazarId" Type="tbl_PortalHaber_Yazar" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PortalHaber_Kaynak" Member="tbl_PortalHaber_Kaynaks">
    <Type Name="tbl_PortalHaber_Kaynak">
      <Column Name="KaynakId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Adi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tbl_PortalHaber_Kaynak_tbl_PortalHaber_Icerik" Member="tbl_PortalHaber_Iceriks" ThisKey="KaynakId" OtherKey="KaynakId" Type="tbl_PortalHaber_Icerik" />
    </Type>
  </Table>
  <Table Name="dbo.VWBANNER" Member="VWBANNERs">
    <Type Name="VWBANNER">
      <Column Name="SbId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SiteAdi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BannerAdi" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="BannerAdet" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PortalHaber_Icerik" Member="tbl_PortalHaber_Iceriks">
    <Type Name="tbl_PortalHaber_Icerik">
      <Column Name="HaberId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HaberBaslik" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="HaberAciklama" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="KategoriId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HaberUrl" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="KaynakId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Site_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Onay_Tarih" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Haber_Resim" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Onay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Banner_Tip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_PortalHaber_Icerik_tbl_PortalHaber_IP" Member="tbl_PortalHaber_IPs" ThisKey="HaberId" OtherKey="Haber_Id" Type="tbl_PortalHaber_IP" />
      <Association Name="tbl_PortalHaber_Icerik_tbl_PortalHaber_OkunmaSayisi" Member="tbl_PortalHaber_OkunmaSayisis" ThisKey="HaberId" OtherKey="Haber_ID" Type="tbl_PortalHaber_OkunmaSayisi" />
      <Association Name="tbl_PortalHaber_Icerik_tbl_PortalHaber_Icerik2" Member="tbl_PortalHaber_Icerik2s" ThisKey="HaberId" OtherKey="HaberId" Type="tbl_PortalHaber_Icerik2" />
      <Association Name="tbl_PortalHaber_kategori_tbl_PortalHaber_Icerik" Member="tbl_PortalHaber_kategori" ThisKey="KategoriId" OtherKey="Kid" Type="tbl_PortalHaber_kategori" IsForeignKey="true" />
      <Association Name="tbl_PortalHaber_Kaynak_tbl_PortalHaber_Icerik" Member="tbl_PortalHaber_Kaynak" ThisKey="KaynakId" OtherKey="KaynakId" Type="tbl_PortalHaber_Kaynak" IsForeignKey="true" />
      <Association Name="tbl_PortalHaber_Site_tbl_PortalHaber_Icerik" Member="tbl_PortalHaber_Site" ThisKey="Site_Id" OtherKey="Site_Id" Type="tbl_PortalHaber_Site" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_PortalHaber_Icerik2" Member="tbl_PortalHaber_Icerik2s">
    <Type Name="tbl_PortalHaber_Icerik2">
      <Column Name="HDid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HaberMetni" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Etiketler" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="YazarId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HaberId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_PortalHaber_Icerik_tbl_PortalHaber_Icerik2" Member="tbl_PortalHaber_Icerik" ThisKey="HaberId" OtherKey="HaberId" Type="tbl_PortalHaber_Icerik" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VWYHABERLIST" Member="VWYHABERLISTs">
    <Type Name="VWYHABERLIST">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EPosta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HaberBaslik" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="HaberAciklama" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>