//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PortalHaber_Yazar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PortalHaber_Yazar()
        {
            this.tbl_PortalHaber_YazarParaTalep = new HashSet<tbl_PortalHaber_YazarParaTalep>();
            this.tbl_PortalHaber_YazarSiteRelation = new HashSet<tbl_PortalHaber_YazarSiteRelation>();
        }
    
        public int YazarId { get; set; }
        public string YName { get; set; }
        public Nullable<int> Tipi { get; set; }
        public string Sifre { get; set; }
        public string EPosta { get; set; }
        public string Resim { get; set; }
    
        public virtual tbl_PortalHaber_Tip tbl_PortalHaber_Tip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PortalHaber_YazarParaTalep> tbl_PortalHaber_YazarParaTalep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PortalHaber_YazarSiteRelation> tbl_PortalHaber_YazarSiteRelation { get; set; }
    }
}
