//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PortalHaber_YazarParaTalep
    {
        public int pt_id { get; set; }
        public Nullable<int> Yazar_Id { get; set; }
        public Nullable<int> Site_Grup_Id { get; set; }
        public Nullable<System.DateTime> Talep_Tarihi { get; set; }
        public Nullable<double> Talep_Miktar { get; set; }
        public Nullable<System.DateTime> Onay_Tarihi { get; set; }
        public Nullable<double> Onay_Miktar { get; set; }
    
        public virtual tbl_PortalHaber_Yazar tbl_PortalHaber_Yazar { get; set; }
    }
}
