//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PortalHaber_PopulerHaberler_Zaman
    {
        public int PHZ_Id { get; set; }
        public Nullable<int> Zaman { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        public virtual tbl_PortalHaber_Site tbl_PortalHaber_Site { get; set; }
    }
}
