//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PortalHaber_Icerik2
    {
        public int HDid { get; set; }
        public string HaberMetni { get; set; }
        public string Etiketler { get; set; }
        public Nullable<int> YazarId { get; set; }
        public Nullable<int> HaberId { get; set; }
    }
}
