//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PortalHaber_Site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PortalHaber_Site()
        {
            this.tbl_PortalHaber_Banner_Site_Relation = new HashSet<tbl_PortalHaber_Banner_Site_Relation>();
            this.tbl_PortalHaber_Icerik = new HashSet<tbl_PortalHaber_Icerik>();
            this.tbl_PortalHaber_PopulerHaberler_Zaman = new HashSet<tbl_PortalHaber_PopulerHaberler_Zaman>();
            this.tbl_PortalHaber_YazarSiteRelation = new HashSet<tbl_PortalHaber_YazarSiteRelation>();
        }
    
        public int Site_Id { get; set; }
        public string Site_Adi { get; set; }
        public Nullable<int> Site_Grubu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PortalHaber_Banner_Site_Relation> tbl_PortalHaber_Banner_Site_Relation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PortalHaber_Icerik> tbl_PortalHaber_Icerik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PortalHaber_PopulerHaberler_Zaman> tbl_PortalHaber_PopulerHaberler_Zaman { get; set; }
        public virtual tbl_PortalHaber_SiteGrubu tbl_PortalHaber_SiteGrubu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PortalHaber_YazarSiteRelation> tbl_PortalHaber_YazarSiteRelation { get; set; }
    }
}
