//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWBANNER
    {
        public int SbId { get; set; }
        public string SiteAdi { get; set; }
        public string BannerAdi { get; set; }
        public Nullable<int> BannerAdet { get; set; }
    }
}
