//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWYHABERLIST
    {
        public int id { get; set; }
        public string EPosta { get; set; }
        public string HaberBaslik { get; set; }
        public string HaberAciklama { get; set; }
    }
}
